import java.util.Scanner;
public class EqualSubstring {
  
  // Method section: generate the substring
  public static String generateSubstring(String string1, int start, int end) {
    String subString = "";
    int count = 0;
    for(int i = start; i < end; i++) {
      subString += string1.charAt(i);
    }
    return subString;
  }
  // Method section: create the method to compare the strings
  public static boolean compareSubstring(String subString1, String subString2) {
    if(subString1.length() != subString2.length()) {
      return false;
    } else {
      for(int i = 0; i < subString1.length(); i++) {
        if(subString1.charAt(i) != subString2.charAt(i)) {
          return false;
        } 
      }
    }
    return true;
  }
  
  public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    
    // Input section: take the inputs from the user
    System.out.println("Enter the string one: ");
    String string1 = sc.next();
    System.out.println("Enter the start index: ");
    int start = sc.nextInt();
    System.out.println("Enter the end index: ");
    int end = sc.nextInt();

    String subString1 = generateSubstring(string1, start, end);
    String subString2 = string1.substring(start, end);
    boolean isSame = compareSubstring(subString1, subString2);


    // Display results: display the results
    if(isSame) {
      System.out.println("The subString generated from built in method is: "+subString2 +"\nsubstring generated by custom method is: "+subString1+"\nBoth the results are same");
    } else {
      System.out.println("The subString generated from built in method is: "+subString2 +"\nsubstring generated by custom method is: "+subString1+"\nBoth the results are not same");
    }
 
    sc.close();
  }
}